// components/HeaderComponent.vue
<template>
  <header
    class="absolute w-full left-0 top-0 z-50 border-b-[1px] border-border"
  >
    <div
      class="flex min-h-16 items-center justify-between box-border max-w-[1000px] my-0 mx-auto px-4"
    >
      <nuxt-link to="/" class="font-bold">stas_fr</nuxt-link>
      <nav>
        <ul class="flex flex-wrap">
          <li class="mr-4"><nuxt-link to="/projects">Projects</nuxt-link></li>
          <li class="mr-4"><nuxt-link to="/skills">Skills</nuxt-link></li>
          <li class=""><nuxt-link to="/contacts">Contacts</nuxt-link></li>
        </ul>
      </nav>
    </div>
  </header>
</template>

<script setup></script>

// src/components/Header.tsx
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

import ThemePicker from "@/components/ThemePicker";

export default function Header() {
  const navBar = [
    {
      name: "Home",
      link: "../",
    },
    {
      name: "Skills",
      link: "../skills",
    },
    {
      name: "Projects",
      link: "../projects",
    },
    {
      name: "Contacts",
      link: "../contacts",
    },
  ];

  return (
    <header className="flex items-center justify-between">
      <div>
        <div>
          <Link to={"/"}>stasfr_homepage</Link>
        </div>

        <nav>
          {navBar.map((item) => (
            <Button asChild key={item.link}>
              <Link to={item.link}>{item.name}</Link>
            </Button>
          ))}
          <ThemePicker />
        </nav>
      </div>
    </header>
  );
}
